{% set name = "fofx" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/fofx/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6b1c7f8c4d17b2a961011e97378e5291623502f577bdb21d0f08ce5f626af894

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba

test:
  requires:
    - python {{ python_min }}
  imports:
    - fofx

about:
  home: https://github.com/esheldon/fofx
  summary: 'Astronomical friends of friends group finding using Source Extractor segmentation maps'
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
